ng-primitives/ng-primitives

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

ci: adding pkg-pr-new

---

apps/documentation/src/app/examples/focus-trap/focus-trap.example.ts
apps/documentation/src/app/pages/utilities/focus-trap.md
packages/ng-primitives/focus-trap/README.md
packages/ng-primitives/focus-trap/ng-package.json
packages/ng-primitives/focus-trap/src/focus-trap/focus-trap.directive.spec.ts
packages/ng-primitives/focus-trap/src/focus-trap/focus-trap.directive.ts
packages/ng-primitives/focus-trap/src/focus-trap/focus-trap.token.ts
packages/ng-primitives/focus-trap/src/index.ts
tsconfig.base.json

feat: adding focus trap primitive

---

apps/documentation/src/app/examples/search/search-field.example.ts
apps/documentation/src/app/pages/primitives/search-field.md
packages/ng-primitives/input/src/input/input.directive.ts
packages/ng-primitives/search/README.md
packages/ng-primitives/search/ng-package.json
packages/ng-primitives/search/src/index.ts
packages/ng-primitives/search/src/search-field/search-field.directive.spec.ts
packages/ng-primitives/search/src/search-field/search-field.directive.ts
packages/ng-primitives/search/src/search-field/search-field.token.ts
tsconfig.base.json

N/A
Adds a search field primitive

feat(search-field): add search field primitive

---

apps/documentation/src/app/pages/primitives/form-field.md
apps/documentation/vite.config.ts

docs: improving form field documentation

---

apps/documentation/src/app/components/navbar/navbar.component.html
apps/documentation/src/app/components/navbar/navbar.component.ts
apps/documentation/src/app/pages/getting-started/introduction.md

docs: adding discord link

---

apps/documentation/src/app/pages/primitives/icons.md

N/A
Based on our algolia searches, one of the most commonly searched for things is icons. While this library does not include icons, we also maintain the Angular Icons library that we use in many examples - adding a page detailing the use of the library an linking to the Angular icons site.

docs: icon docs

---

apps/documentation/src/app/examples/pagination/pagination.example.ts
apps/documentation/src/app/pages/primitives/pagination.md
packages/ng-primitives/pagination/README.md
packages/ng-primitives/pagination/ng-package.json
packages/ng-primitives/pagination/src/index.ts
packages/ng-primitives/pagination/src/pagination-button/pagination-button.directive.spec.ts
packages/ng-primitives/pagination/src/pagination-button/pagination-button.directive.ts
packages/ng-primitives/pagination/src/pagination-button/pagination-button.token.ts
packages/ng-primitives/pagination/src/pagination-first/pagination-first.directive.spec.ts
packages/ng-primitives/pagination/src/pagination-first/pagination-first.directive.ts
packages/ng-primitives/pagination/src/pagination-first/pagination-first.token.ts
packages/ng-primitives/pagination/src/pagination-last/pagination-last.directive.spec.ts
packages/ng-primitives/pagination/src/pagination-last/pagination-last.directive.ts
packages/ng-primitives/pagination/src/pagination-last/pagination-last.token.ts
packages/ng-primitives/pagination/src/pagination-next/pagination-next.directive.spec.ts
packages/ng-primitives/pagination/src/pagination-next/pagination-next.directive.ts
packages/ng-primitives/pagination/src/pagination-next/pagination-next.token.ts
packages/ng-primitives/pagination/src/pagination-previous/pagination-previous.directive.spec.ts
packages/ng-primitives/pagination/src/pagination-previous/pagination-previous.directive.ts
packages/ng-primitives/pagination/src/pagination-previous/pagination-previous.token.ts
packages/ng-primitives/pagination/src/pagination/pagination.directive.spec.ts
packages/ng-primitives/pagination/src/pagination/pagination.directive.ts
packages/ng-primitives/pagination/src/pagination/pagination.token.ts
tsconfig.base.json

feat: pagination

---

packages/ng-primitives/ng-package.json

Closes #28
Closes #28
Add missing generators file

fix: adding missing generators file

---

apps/documentation/src/app/components/navbar/navbar.component.html
apps/documentation/src/styles.css

Closes #31
| Light mode  | Dark mode  | 
|---|---|
| ![image](https://github.com/user-attachments/assets/3d96cfe0-04e0-40ea-8b94-fb850a476503)  | ![image](https://github.com/user-attachments/assets/c6388f15-0891-4704-a618-6a75c27ec0c0)  |

fix(docs): Navbar Right-hand Side Buttons Not Clickable on Mobile

---

apps/documentation/src/app/examples/menu/menu.example.ts
apps/documentation/src/app/pages/primitives/menu.md
apps/documentation/src/styles.css
packages/ng-primitives/menu/README.md
packages/ng-primitives/menu/ng-package.json
packages/ng-primitives/menu/src/index.ts
packages/ng-primitives/menu/src/menu-item/menu-item.directive.spec.ts
packages/ng-primitives/menu/src/menu-item/menu-item.directive.ts
packages/ng-primitives/menu/src/menu-item/menu-item.token.ts
packages/ng-primitives/menu/src/menu-trigger/menu-trigger.directive.spec.ts
packages/ng-primitives/menu/src/menu-trigger/menu-trigger.directive.ts
packages/ng-primitives/menu/src/menu-trigger/menu-trigger.token.ts
packages/ng-primitives/menu/src/menu/menu.directive.spec.ts
packages/ng-primitives/menu/src/menu/menu.directive.ts
packages/ng-primitives/menu/src/menu/menu.token.ts
tsconfig.base.json

feat(menu): menu primitive

---

apps/documentation/src/styles.css

Closes #34
The issue has been resolved by updating the Algolia search bar's styling to align with the dark mode theme of the application.

fix(docs): Apply darkmode on Algolia searchBar

---

packages/ng-primitives/internal/src/disabled/disabled.ts

N/A
Resolving issue where the disabled state does not get propagated to host directives

fix: button disabled state interaction handling

---

packages/ng-primitives/pagination/src/pagination-button/pagination-button.directive.ts
packages/ng-primitives/pagination/src/pagination-first/pagination-first.directive.ts
packages/ng-primitives/pagination/src/pagination-last/pagination-last.directive.ts
packages/ng-primitives/pagination/src/pagination-next/pagination-next.directive.ts
packages/ng-primitives/pagination/src/pagination-previous/pagination-previous.directive.ts

N/A
Ensuring events are fired when enter or space key is pressed

fix(pagination): trigger page events with keyboard

---

packages/ng-primitives/interactions/src/focus-visible/focus-visible.directive.ts
packages/ng-primitives/interactions/src/press/press.directive.ts

fix(interactions): ensuring interactions consider disabled state

---

packages/ng-primitives/dialog/src/dialog-trigger/dialog-trigger.directive.ts
packages/ng-primitives/tooltip/src/config/tooltip.config.ts
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.directive.ts

Fixing issue where tooltip config relied on document.body causing ssr issues.
N/A

fix(tooltip): tooltip ssr fix

---

packages/ng-primitives/dialog/src/dialog-trigger/dialog-trigger.directive.ts

Closes #44
Separate the dialog from the view container ref of the trigger

fix(dialog): separate dialog from trigger view ref

---

apps/documentation/src/app/examples/checkbox/checkbox-form-field.example.ts
apps/documentation/src/app/pages/primitives/checkbox.md
packages/ng-primitives/utils/src/index.ts
packages/ng-primitives/utils/src/signals/async.ts

docs: improving checkbox docs and example

---

apps/documentation/src/app/examples/checkbox/checkbox-form-field.example.ts
apps/documentation/src/app/examples/checkbox/checkbox.example.ts
packages/ng-primitives/interactions/src/focus-visible/focus-visible.directive.spec.ts
packages/ng-primitives/interactions/src/focus-visible/focus-visible.directive.ts
packages/ng-primitives/utils/src/signals/async.ts

Invalidate isFocused signal in order to prevent stale data-focus-visible attribute state. No tests, WIP.
Closes #

fix(focus-visible): data-focus-visible attribute

---

apps/documentation/src/app/examples/popover/popover.example.ts
apps/documentation/src/app/pages/primitives/popover.md
packages/ng-primitives/popover/README.md
packages/ng-primitives/popover/ng-package.json
packages/ng-primitives/popover/src/config/popover.config.ts
packages/ng-primitives/popover/src/index.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.directive.spec.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.directive.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.token.ts
packages/ng-primitives/popover/src/popover/popover.directive.spec.ts
packages/ng-primitives/popover/src/popover/popover.directive.ts
packages/ng-primitives/popover/src/popover/popover.token.ts
tsconfig.base.json

Closes #19 
Add new Popover primitive

feat(popover): add new popover primitive

---

apps/documentation/src/app/examples/popover/popover.example.ts
apps/documentation/src/app/pages/primitives/popover.md
packages/ng-primitives/popover/README.md
packages/ng-primitives/popover/ng-package.json
packages/ng-primitives/popover/src/config/popover.config.ts
packages/ng-primitives/popover/src/index.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.directive.spec.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.directive.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.token.ts
packages/ng-primitives/popover/src/popover/popover.directive.spec.ts
packages/ng-primitives/popover/src/popover/popover.directive.ts
packages/ng-primitives/popover/src/popover/popover.token.ts
tsconfig.base.json

fix: popover - fixing merge issue

---

apps/documentation/src/app/examples/accordion/accordion.example.ts
apps/documentation/src/app/examples/dialog/dialog.example.ts
apps/documentation/src/app/pages/primitives/accordion.md
apps/documentation/src/app/pages/primitives/dialog.md
apps/documentation/src/app/pages/primitives/menu.md
apps/documentation/src/app/pages/primitives/tooltip.md
packages/ng-primitives/accordion/src/accordion-trigger/accordion-trigger.directive.ts
packages/ng-primitives/dialog/src/dialog-trigger/dialog-trigger.directive.ts
packages/ng-primitives/interactions/src/focus-visible/focus-visible.directive.spec.ts
packages/ng-primitives/interactions/src/focus-visible/focus-visible.directive.ts

Closes #
To fully support dialog focus management, we need to allow program origin in NgpFocusVisible.
+ fix accordion styling

fix: focus management

---

apps/documentation/src/app/examples/toast/toast.example.ts
apps/documentation/src/app/pages/primitives/avatar.md
apps/documentation/src/app/pages/primitives/toast.md
packages/ng-primitives/toast/README.md
packages/ng-primitives/toast/ng-package.json
packages/ng-primitives/toast/src/config/toast.config.ts
packages/ng-primitives/toast/src/index.ts
packages/ng-primitives/toast/src/toast/toast-ref.ts
packages/ng-primitives/toast/src/toast/toast.directive.spec.ts
packages/ng-primitives/toast/src/toast/toast.directive.ts
packages/ng-primitives/toast/src/toast/toast.token.ts
tsconfig.base.json

feat: toast primitive

---

packages/ng-primitives/schematics/button/files/__name__.component.ts.template

Closes #64 
Passing the disabled input to the NgpButton directive.

feat(button): disabled attribute for generator

---

packages/ng-primitives/internal/src/style-injector/style-injector.ts

Closes #68 
Resolving ssr issue

fix(autofill): resolving ssr issue

---

packages/ng-primitives/pagination/src/pagination/pagination.directive.ts

fix(pagination): making page count optional

---

packages/ng-primitives/schematics/form-field/schema.json
packages/ng-primitives/schematics/input/schema.json
packages/tools/src/generators/documentation/schema.json
packages/tools/src/generators/example/schema.json
packages/tools/src/generators/primitive/schema.json
packages/tools/src/generators/schematic/schema.json

Closes #79 
Correcting schema.json url

fix: schematics error

---

packages/ng-primitives/tooltip/src/tooltip/tooltip.directive.ts

Closes #83 
Resolving ssr tooltip issue

fix(tooltip): fix ssr issue

---

apps/documentation/src/app/examples/popover/popover.example.ts

Fix the popover documentation box shadow when the popover is open

Fix: Popover Docs

---

nx.json
packages/ng-primitives/accordion/src/index.ts
packages/ng-primitives/autofill/src/index.ts
packages/ng-primitives/avatar/src/index.ts
packages/ng-primitives/button/src/index.ts
packages/ng-primitives/checkbox/src/index.ts
packages/ng-primitives/date-picker/src/index.ts
packages/ng-primitives/dialog/src/index.ts
packages/ng-primitives/focus-trap/src/index.ts
packages/ng-primitives/form-field/src/index.ts
packages/ng-primitives/input/src/index.ts
packages/ng-primitives/interactions/src/index.ts
packages/ng-primitives/menu/src/index.ts
packages/ng-primitives/pagination/src/index.ts
packages/ng-primitives/popover/src/index.ts
packages/ng-primitives/radio/src/index.ts
packages/ng-primitives/roving-focus/src/index.ts
packages/ng-primitives/search/src/index.ts
packages/ng-primitives/select/src/index.ts
packages/ng-primitives/slider/src/index.ts
packages/ng-primitives/switch/src/index.ts
packages/ng-primitives/tabs/src/index.ts
packages/ng-primitives/textarea/src/index.ts
packages/ng-primitives/toast/src/index.ts
packages/ng-primitives/tooltip/src/index.ts
packages/tools/src/generators/token/generator.ts

refactor: expose inject functions

---

packages/ng-primitives/internal/src/interactions/focus-visible.ts
packages/ng-primitives/menu/src/menu-trigger/menu-trigger.directive.ts

N/A
Allow support for ngpMenuTrigger as a host directive.

fix(menu): allow menu trigger host binding

---

packages/ng-primitives/utils/src/ui/dimensions.ts

refactor: stop using deprecated AfterRenderPhase API

---

apps/documentation/src/app/components/example/example.component.ts

docs: fixing example code

---

apps/documentation/src/app/examples/file-upload/file-upload.example.ts
apps/documentation/src/app/pages/primitives/file-upload.md
package.json
packages/ng-primitives/file-upload/src/file-upload/file-upload.directive.ts
pnpm-lock.yaml

Closes #
Adds a binding for the `cancel` event on a file input that was missing earlier. This allows the developer to define behaviour when the user clicks "cancel" in the ui or when they select the same file again.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#detecting_cancellations

update(file-upload): add binding for cancel event

---

package.json

build: specifying package manager

---

apps/documentation/src/app/examples/listbox/listbox-select.example.ts
package.json

docs update

---

apps/documentation/src/app/pages/primitives/popover.md
packages/ng-primitives/popover/src/config/popover.config.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.directive.ts
packages/ng-primitives/popover/src/popover/popover.directive.ts

Closes #108 
Adding scroll blocking to popover

feat(popover): scroll blocking

---

packages/ng-primitives/dialog/src/index.ts

Closes #115 
Adding missing import

fix(dialog): adding missing NgpDialogRef export

---

apps/documentation/src/app/examples/listbox/listbox-select.example.ts
apps/documentation/src/app/examples/popover/popover.example.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.directive.ts
packages/ng-primitives/popover/src/popover/popover.directive.ts
packages/ng-primitives/popover/src/utils/transform-origin.ts

feat(popover): adding entry animation support

---

apps/documentation/src/app/examples/separator/separator.example.ts
apps/documentation/src/app/pages/primitives/accordion.md
apps/documentation/src/app/pages/primitives/avatar.md
apps/documentation/src/app/pages/primitives/popover.md
apps/documentation/src/app/pages/primitives/separator.md
apps/documentation/src/app/pages/primitives/tabs.md
apps/documentation/src/app/pages/primitives/toast.md
apps/documentation/src/app/pages/primitives/tooltip.md
packages/ng-primitives/separator/README.md
packages/ng-primitives/separator/ng-package.json
packages/ng-primitives/separator/src/config/separator.config.ts
packages/ng-primitives/separator/src/index.ts
packages/ng-primitives/separator/src/separator/separator.directive.spec.ts
packages/ng-primitives/separator/src/separator/separator.directive.ts
packages/ng-primitives/separator/src/separator/separator.token.ts
packages/tools/src/generators/directive/generator.ts
packages/tools/src/generators/documentation/files/__name__.md.template
tsconfig.base.json

feat(separator): adding separator primitive

---

apps/documentation/src/app/examples/toggle-group/toggle-group-multiple.example.ts
apps/documentation/src/app/examples/toggle-group/toggle-group.example.ts
apps/documentation/src/app/pages/primitives/toggle-group.md
packages/ng-primitives/accordion/src/accordion/accordion.directive.ts
packages/ng-primitives/common/src/index.ts
packages/ng-primitives/common/src/types/orientation.ts
packages/ng-primitives/internal/src/orientation/orientation.ts
packages/ng-primitives/radio/src/radio-group/radio-group.directive.ts
packages/ng-primitives/roving-focus/src/roving-focus-group/roving-focus-group.directive.ts
packages/ng-primitives/separator/src/config/separator.config.ts
packages/ng-primitives/separator/src/separator/separator.directive.ts
packages/ng-primitives/slider/src/slider/slider.directive.ts
packages/ng-primitives/tabs/src/config/tabs.config.ts
packages/ng-primitives/tabs/src/tabset/tabset.directive.ts
packages/ng-primitives/toggle-group/README.md
packages/ng-primitives/toggle-group/ng-package.json
packages/ng-primitives/toggle-group/src/config/toggle-group.config.ts
packages/ng-primitives/toggle-group/src/index.ts
packages/ng-primitives/toggle-group/src/toggle-group-item/toggle-group-item.directive.ts
packages/ng-primitives/toggle-group/src/toggle-group-item/toggle-group-item.token.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.directive.spec.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.directive.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.token.ts
tsconfig.base.json

feat(toggle-group): adding toggle group primitive

---

apps/documentation/src/app/examples/toolbar/toolbar.example.ts
apps/documentation/src/app/pages/primitives/toggle-group.md
apps/documentation/src/app/pages/primitives/toolbar.md
packages/ng-primitives/roving-focus/src/roving-focus-group/roving-focus-group.directive.ts
packages/ng-primitives/roving-focus/src/roving-focus-group/roving-focus-group.token.ts
packages/ng-primitives/toolbar/README.md
packages/ng-primitives/toolbar/ng-package.json
packages/ng-primitives/toolbar/src/index.ts
packages/ng-primitives/toolbar/src/toolbar/toolbar.directive.spec.ts
packages/ng-primitives/toolbar/src/toolbar/toolbar.directive.ts
packages/ng-primitives/toolbar/src/toolbar/toolbar.token.ts
packages/tools/src/generators/directive/files/__fileName__.directive.ts.template
packages/tools/src/generators/token/files/__fileName__/__fileName__.token.ts.template
tsconfig.base.json

feat(toolbar): adding toolbar primitive

---

packages/ng-primitives/checkbox/src/checkbox/checkbox.directive.ts
packages/ng-primitives/checkbox/src/checkbox/checkbox.token.ts
packages/ng-primitives/forms/README.md
packages/ng-primitives/forms/ng-package.json
packages/ng-primitives/forms/src/control-state.ts
packages/ng-primitives/forms/src/index.ts
tsconfig.base.json

feat: form control state

---

apps/documentation/src/app/components/snippet/snippet.component.ts
packages/ng-primitives/schematics/ng-generate/templates/accordion/accordion-item.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/accordion/accordion.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/avatar/avatar.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/button/button.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/checkbox/checkbox.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/date-picker/date-picker.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/form-field/form-field.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/input/input.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/pagination/pagination.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/progress/progress.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/radio/radio-group.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/radio/radio-item.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/slider/slider.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/switch/switch.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/tabs/tabs.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/toggle-group/toggle-group-item.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/toggle-group/toggle-group.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/schematics/ng-generate/templates/toggle/toggle.__fileSuffix@dasherize__.ts.template
packages/tools/src/generators/templates/templates.ts

docs: adding information on style imports

---

apps/documentation/src/app/examples/radio/radio.example.ts
apps/documentation/src/app/examples/switch/switch.example.ts
packages/ng-primitives/checkbox/src/checkbox/checkbox-state.ts
packages/ng-primitives/checkbox/src/checkbox/checkbox.ts
packages/ng-primitives/date-picker/src/date-picker/date-picker-state.ts
packages/ng-primitives/date-picker/src/date-picker/date-picker.ts
packages/ng-primitives/example-theme/index.css
packages/ng-primitives/pagination/src/pagination/pagination-state.ts
packages/ng-primitives/pagination/src/pagination/pagination.ts
packages/ng-primitives/progress/src/progress/progress-state.ts
packages/ng-primitives/progress/src/progress/progress.ts
packages/ng-primitives/radio/src/radio-group/radio-group-state.ts
packages/ng-primitives/radio/src/radio-group/radio-group.ts
packages/ng-primitives/radio/src/radio-item/radio-item-state.ts
packages/ng-primitives/radio/src/radio-item/radio-item.ts
packages/ng-primitives/slider/src/slider/slider-state.ts
packages/ng-primitives/slider/src/slider/slider.ts
packages/ng-primitives/state/src/state.ts
packages/ng-primitives/switch/src/switch/switch-state.ts
packages/ng-primitives/switch/src/switch/switch.ts
packages/ng-primitives/tabs/src/tabset/tabset-state.ts
packages/ng-primitives/tabs/src/tabset/tabset.ts
packages/ng-primitives/toggle-group/src/toggle-group-item/toggle-group-item-state.ts
packages/ng-primitives/toggle-group/src/toggle-group-item/toggle-group-item.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group-state.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.ts
packages/ng-primitives/toggle/src/toggle/toggle-state.ts
packages/ng-primitives/toggle/src/toggle/toggle.ts
packages/tools/src/generators/directive/files/__fileName__.ts.template
packages/tools/src/generators/state/files/__fileName__/__fileName__-state.ts.template

refactor: simplifying state managment

---

packages/ng-primitives/collection.json

fix: re-adding support for nx add

---

apps/documentation/src/app/examples/dialog/dialog-data.example.ts
apps/documentation/src/app/examples/dialog/dialog-drawer.example.ts
apps/documentation/src/app/pages/primitives/dialog.md
packages/ng-primitives/dialog/src/dialog-overlay/dialog-overlay.ts
packages/ng-primitives/dialog/src/dialog/dialog-ref.ts
packages/ng-primitives/dialog/src/dialog/dialog.service.ts
packages/ng-primitives/dialog/src/dialog/dialog.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation.spec.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation.ts
packages/ng-primitives/internal/src/index.ts

feat: adding support for dialog animations

---

apps/documentation/src/app/components/example/example.ng.html
apps/documentation/src/app/components/example/example.ts

docs: simplifying code examples and adding stylesheet import info

---

apps/components/src/app/app.routes.ts
apps/components/src/app/app.ts
apps/components/src/app/textarea/app.ts
apps/components/src/app/textarea/textarea.ts
apps/documentation/src/app/pages/primitives/textarea.md
packages/ng-primitives/schematics/ng-generate/schema.d.ts
packages/ng-primitives/schematics/ng-generate/schema.json

feat: text area reusable component

---

apps/components/src/app/app.routes.ts
apps/components/src/app/app.ts
apps/components/src/app/separator/app.ts
apps/components/src/app/separator/separator.ts
apps/documentation/src/app/pages/primitives/separator.md
packages/ng-primitives/schematics/ng-generate/schema.d.ts
packages/ng-primitives/schematics/ng-generate/schema.json
packages/ng-primitives/schematics/ng-generate/templates/separator/separator.__fileSuffix@dasherize__.ts.template

This PR introduces reusable component and schematic for separator
Closes #

feat: add separator reusable component

---

packages/ng-primitives/menu/src/menu-item/menu-item.ts
packages/ng-primitives/menu/src/menu/menu.ts
packages/ng-primitives/menu/src/submenu-trigger/submenu-trigger.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts

fix(menu): avoid submenus being duplicated

---

apps/components/src/app/separator/separator.ts
packages/ng-primitives/accordion/src/accordion-item/accordion-item.ts
packages/ng-primitives/accordion/src/accordion/accordion.ts
packages/ng-primitives/checkbox/src/checkbox/checkbox.ts
packages/ng-primitives/date-picker/src/date-picker/date-picker.ts
packages/ng-primitives/file-upload/src/file-upload/file-upload.ts
packages/ng-primitives/listbox/src/listbox/listbox.ts
packages/ng-primitives/pagination/src/pagination/pagination.ts
packages/ng-primitives/radio/src/radio-group/radio-group.ts
packages/ng-primitives/state/src/index.ts
packages/ng-primitives/switch/src/switch/switch.ts
packages/ng-primitives/tabs/src/tabset/tabset.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.ts

refactor(state): outputs should not be part of the created state

---

.github/workflows/ci.yml
packages/ng-primitives/interactions/src/focus-visible/focus-visible.spec.ts
packages/ng-primitives/state/src/index.ts
packages/ng-primitives/toggle/src/toggle/toggle.spec.ts

build: fixing unit tests

---

packages/ng-primitives/input/src/input/input.ts
packages/ng-primitives/search/src/search-clear/search-clear.ts
packages/ng-primitives/search/src/search/search.spec.ts
packages/ng-primitives/search/src/search/search.ts

refactor: search simplify

---

packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts

fix(menu): resolve open issues on touch devices

---

apps/documentation/src/app/examples/file-upload/file-dropzone.example.ts
apps/documentation/src/app/pages/primitives/file-upload.md
packages/ng-primitives/file-upload/src/file-dropzone/file-dropzone-state.ts
packages/ng-primitives/file-upload/src/file-dropzone/file-dropzone.ts
packages/ng-primitives/file-upload/src/file-upload/file-upload.ts
packages/ng-primitives/file-upload/src/index.ts

feat(file-upload): dropzone

---

packages/ng-primitives/dialog/src/dialog-trigger/dialog-trigger.ts
packages/ng-primitives/dialog/src/dialog/dialog.service.ts
packages/ng-primitives/schematics/ng-generate/templates/dialog/dialog.__fileSuffix@dasherize__.ts.template

fix(dialog): resolve dialog view container ref issue

---

apps/components/src/app/accordion/accordion-item.ts
apps/documentation/src/app/examples/accordion/accordion.example.ts
apps/documentation/src/app/examples/dialog/dialog-drawer.example.ts
apps/documentation/src/app/examples/popover/popover.example.ts
apps/documentation/src/app/examples/tooltip/tooltip.example.ts
apps/documentation/src/app/pages/primitives/accordion.md
apps/documentation/src/app/pages/primitives/popover.md
apps/documentation/src/app/pages/primitives/tooltip.md
packages/ng-primitives/accordion/src/accordion-content/accordion-content.ts

feat(accordion): animation support

---

apps/components/src/app/app.routes.ts
apps/components/src/app/app.ts
apps/components/src/app/toast/app.ts
apps/components/src/app/toast/toast.ts
apps/documentation/src/app/pages/primitives/toast.md
packages/ng-primitives/schematics/ng-generate/schema.d.ts
packages/ng-primitives/schematics/ng-generate/schema.json
packages/ng-primitives/toast/src/toast/toast.ts

feat(toast): reusable component

---

packages/ng-primitives/toast/src/toast/toast.ts

fix(toast): ensure toasts always stack

---

packages/ng-primitives/radio/src/radio-group/radio-group.spec.ts
packages/ng-primitives/radio/src/radio-group/radio-group.ts
packages/ng-primitives/tabs/src/tab-button/tab-button.ts
packages/ng-primitives/tabs/src/tabset/tabset.spec.ts
packages/ng-primitives/tabs/src/tabset/tabset.ts

fix(radio,tabs): ensure valueChange events only emit once

---

apps/documentation/src/app/examples/popover/popover.example.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation-manager.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation.ts
packages/ng-primitives/internal/src/index.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/popover/src/popover/popover.ts

feat(popover): exit animations

---

apps/components/src/app/app.routes.ts
apps/components/src/app/app.ts
apps/components/src/app/toolbar/app.ts
apps/components/src/app/toolbar/toolbar-button.ts
apps/components/src/app/toolbar/toolbar.ts
apps/documentation/src/app/pages/primitives/toolbar.md
packages/ng-primitives/schematics/ng-generate/schema.d.ts
packages/ng-primitives/schematics/ng-generate/schema.json

Closes: #158
Closes #158 
This PR introduces reusable component for toolbar

feat: add reusable toolbar component

---

apps/documentation/src/app/examples/tooltip/tooltip.example.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation-manager.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.ts
packages/ng-primitives/tooltip/src/tooltip/tooltip.ts

feat(tooltip): tooltip exit animation

---

apps/documentation/src/app/examples/menu/menu.example.ts
apps/documentation/src/app/examples/menu/submenu.example.ts

feat(menu): add exit animation support (#149)

---

apps/documentation/src/app/examples/file-upload/file-dropzone.example.ts
apps/documentation/src/app/examples/file-upload/file-upload.example.ts
packages/ng-primitives/file-upload/src/file-dropzone/file-dropzone.ts
packages/ng-primitives/file-upload/src/file-upload/file-upload.ts

fix(file-upload): fixing accepted types

---

apps/documentation/src/app/examples/menu/menu.example.ts
packages/ng-primitives/popover/src/index.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger-state.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/popover/src/popover/popover-token.ts
packages/ng-primitives/state/src/index.ts
packages/ng-primitives/utils/src/helpers/disposables.ts

feat(popover): popover component support

---

packages/ng-primitives/focus-trap/src/focus-trap/focus-trap-state.ts
packages/ng-primitives/focus-trap/src/focus-trap/focus-trap.ts
packages/ng-primitives/focus-trap/src/index.ts
packages/ng-primitives/internal/src/exit-animation/exit-animation.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/popover/src/popover/popover.ts

fix(menu): menu animation fixes

---

apps/components/src/app/toolbar/app.ts
apps/components/src/app/toolbar/toolbar.ts
packages/ng-primitives/toolbar/src/index.ts
packages/ng-primitives/toolbar/src/toolbar/toolbar-state.ts
packages/ng-primitives/toolbar/src/toolbar/toolbar.ts

fix(toolbar): ensure orientation defaults to horizontal

---

apps/documentation/src/app/pages/primitives/dialog.md
packages/ng-primitives/dialog/src/dialog-overlay/dialog-overlay.ts
packages/ng-primitives/dialog/src/dialog-trigger/dialog-trigger.ts

feat(dialog): allow backdrop click to be disabled

---

packages/ng-primitives/file-upload/src/file-upload/file-upload.ts

fix(file-upload): allow same file reupload

---

.github/workflows/ci.yml
apps/documentation/src/app/pages/primitives/meter.md
package.json
pnpm-lock.yaml

build: bumping node version and pnpm version

---

apps/components/src/app/progress/progress.ts
apps/documentation/src/app/pages/primitives/popover.md
packages/ng-primitives/button/src/button/button.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts

fix(button): resolve data-disabled attribute

---

apps/components/src/app/progress/progress.ts
package.json
packages/ng-primitives/dialog/src/dialog-trigger/dialog-trigger.ts
packages/ng-primitives/dialog/src/dialog/dialog.service.ts
packages/ng-primitives/focus-trap/src/focus-trap/focus-trap.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/popover/src/popover/popover.ts
pnpm-lock.yaml

fix(dialog): resolving focus issue

---

apps/documentation/src/app/app.ts
apps/documentation/src/app/components/quick-links/quick-links.ts
apps/documentation/src/app/components/side-navigation/side-navigation.ts
apps/documentation/src/app/pages/getting-started.page.ts
apps/documentation/src/app/pages/interactions.page.ts
apps/documentation/src/app/pages/primitives.page.ts
apps/documentation/src/app/pages/utilities.page.ts

docs: sticky quicklinks

---

packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/popover/src/popover/popover.ts

fix(listbox): resolve focus trap issue

---

apps/documentation/src/app/pages/primitives/popover.md
apps/documentation/src/app/pages/primitives/tooltip.md

docs(popover): adding styling documentation

---

packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/portal/README.md
packages/ng-primitives/portal/ng-package.json
packages/ng-primitives/portal/src/index.ts
packages/ng-primitives/portal/src/portal.ts
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.ts
tsconfig.base.json

fix(popover): detect changes issue

---

.gitignore
.vscode/settings.json
packages/ng-primitives/checkbox/src/checkbox/checkbox.ts
packages/ng-primitives/form-field/src/form-control/form-control-state.ts
packages/ng-primitives/form-field/src/form-control/form-control.ts
packages/ng-primitives/form-field/src/index.ts
packages/ng-primitives/input/src/input/input.ts
packages/ng-primitives/radio/src/radio-group/radio-group.ts
packages/ng-primitives/select/src/select/select.ts
packages/ng-primitives/slider/src/slider/slider.ts
packages/ng-primitives/textarea/src/textarea/textarea.ts

fix(checkbox): id syncing issue

---

packages/ng-primitives/resize/src/utils/resize.ts

fix(resize): support server environments

---

packages/ng-primitives/form-field/src/form-control/form-control.ts
packages/ng-primitives/input/src/input/input.spec.ts
packages/ng-primitives/utils/src/forms/status.ts
packages/ng-primitives/utils/src/index.ts

feat(form-control): add support for standalone form control

---

apps/documentation/src/styles.css
packages/ng-primitives/portal/src/index.ts
packages/ng-primitives/portal/src/overlay.ts
packages/ng-primitives/portal/src/scroll-strategy.ts

Closes #
Resolve issue where scroll blocking relied on CDK overlay stylesheet. Now this is no longer required.

fix(menu): resolve scroll blocking not working

---

packages/ng-primitives/input/src/input/input.spec.ts
packages/ng-primitives/input/src/input/input.ts

fix(input): correct disabled attribute

---

packages/ng-primitives/toggle-group/src/config/toggle-group-config.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.spec.ts
packages/ng-primitives/toggle-group/src/toggle-group/toggle-group.ts

feat(toggle-group): adding option to allow deselection

---

apps/components-e2e/src/reusable-components/select.spec.ts
apps/components/src/app/app.ts
apps/components/src/app/pages/reusable-components/select/index.page.ts
apps/components/src/app/pages/reusable-components/select/select.ts
apps/documentation/src/app/pages/primitives/select.md
packages/ng-primitives/schematics/ng-generate/schema.d.ts
packages/ng-primitives/schematics/ng-generate/schema.json

Closes #155
This PR adds reusable component for select

feat: add select reusable component

---

packages/ng-primitives/slider/src/slider-thumb/slider-thumb.ts

fix(slider): resolve dragging issue

---

packages/ng-primitives/combobox/src/combobox/combobox.ts
packages/ng-primitives/portal/src/overlay.ts

fix(combobox): prevent unexpected scroll

---

apps/components/src/app/pages/reusable-components/popover/popover.ts
apps/components/src/app/pages/reusable-components/tooltip/tooltip.ts
packages/ng-primitives/menu/src/menu-trigger/menu-trigger.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/portal/src/overlay-token.ts
packages/ng-primitives/portal/src/overlay.ts
packages/ng-primitives/schematics/ng-generate/templates/tooltip/tooltip.__fileSuffix@dasherize__.ts.template
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.ts

Closes #297
The tooltip context is now provided as a signal instead of a value to allow it to be updated dynamically

fix(overlay)!: context injection is now a signal

---

packages/ng-primitives/form-field/src/form-control/form-control.ts
packages/ng-primitives/input/src/input/input.spec.ts
packages/ng-primitives/input/src/input/input.ts

fix(input): fix form disabled issue

---

apps/documentation/src/app/examples/dialog/dialog-data.example.ts
packages/ng-primitives/dialog/src/dialog/dialog-ref.ts
packages/ng-primitives/dialog/src/dialog/dialog-state.ts
packages/ng-primitives/dialog/src/dialog/dialog.service.ts
packages/ng-primitives/dialog/src/dialog/dialog.ts

feat: return dialog close value

---

apps/documentation/src/app/examples/accordion/accordion.tailwind.example.ts

feat: add accordion tailwind example

---

packages/ng-primitives/button/src/button/button.ts
packages/ng-primitives/menu/src/menu-item/menu-item.ts

fix(menu): fix menu disabled state

---

apps/documentation/src/app/examples/dialog/dialog.tailwind.example.ts
packages/ng-primitives/combobox/src/combobox/combobox.spec.ts

feat: add dialog tailwind example

---

apps/documentation/src/app/examples/file-upload/file-upload.tailwind.example.ts

feat: add file-upload tailwind example

---

context7.json

feat: adding support for context7

---

apps/documentation/src/app/pages/primitives/combobox.md
packages/ng-primitives/combobox/src/combobox-input/combobox-input.ts
packages/ng-primitives/combobox/src/combobox/combobox.ts

feat(combobox): combobox adding status attributes

---

apps/documentation/src/app/examples/tabs/tabs.example.ts
packages/ng-primitives/tabs/src/tab-button/tab-button.ts
packages/ng-primitives/tabs/src/tab-panel/tab-panel.ts
packages/ng-primitives/tabs/src/tabset/tabset.spec.ts
packages/ng-primitives/tabs/src/tabset/tabset.ts

fix(tab): disabled button

---

.github/copilot-instructions.md
apps/documentation/src/app/pages/primitives/tooltip.md
packages/ng-primitives/internal/src/exit-animation/exit-animation.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/popover/src/popover/popover.ts
packages/ng-primitives/portal/src/overlay.ts
packages/ng-primitives/tooltip/src/config/tooltip-config.ts
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.ts
packages/ng-primitives/tooltip/src/tooltip/tooltip.ts

fix(tooltip): resolve accessibility issues

---

apps/components/src/app/pages/reusable-components/toast/toast.ts
apps/documentation/src/app/examples/toast/toast.example.ts
packages/ng-primitives/accordion/src/accordion-item/accordion-item.ts
packages/ng-primitives/combobox/src/combobox-option/combobox-option.ts
packages/ng-primitives/radio/src/radio-item/radio-item.ts
packages/ng-primitives/tabs/src/tab-button/tab-button.ts
packages/ng-primitives/tabs/src/tab-panel/tab-panel.ts
packages/ng-primitives/toggle-group/src/toggle-group-item/toggle-group-item.ts
packages/tools/src/executors/api-extraction/api-extraction.ts

fix(accordion): provide default values

---

apps/documentation/index.html
apps/documentation/src/app/pages/index.page.ts
apps/documentation/src/styles.css

Closes #378 
Fixes the dark mode styles for the new landing page
https://www.loom.com/share/bdc21433b2524fdfa1f728fc80aed269
https://www.loom.com/share/eeb149eb66cf48d0a1a3cd01ee0aff05

docs: fix dark mode colors

---

packages/ng-primitives/toast/src/config/toast-config.ts
packages/ng-primitives/toast/src/toast/toast-manager.ts
packages/ng-primitives/toast/src/toast/toast-options.ts
packages/ng-primitives/toast/src/toast/toast.ts

Closes #384
- Applies offsetTop and offsetBottom top centered toasts
- Adds placement as config option

fix(toast): toast placement and offset

---

packages/ng-primitives/menu/src/menu/menu.ts
packages/ng-primitives/popover/src/popover/popover.ts
packages/ng-primitives/portal/src/overlay.ts
packages/ng-primitives/tooltip/src/tooltip/tooltip.ts

feat(overlay): allow multiple elements within overlay

---

apps/documentation/src/app/pages/(documentation)/primitives/tooltip.md
packages/ng-primitives/tooltip/src/config/tooltip-config.ts
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.ts

docs(tooltip): add missing props and fix default value

---

apps/documentation/src/app/pages/index.page.ts

N/A
Adding "partnered with Coralogix" chip (and link) above the title, and updated one of the feature sections to mention it also. Happy to hear suggestions!
Link to preview changes is available here:
https://deploy-preview-393--ng-primitives.netlify.app/

docs: add coralogix

---

packages/ng-primitives/portal/src/overlay.ts

fix(tooltip): ensure overlays are hidden when an element is hidden

---

apps/documentation/src/app/examples/meter/meter.tailwind.example.ts

feat: add meter tailwind example

---

apps/documentation/src/app/examples/popover/popover.tailwind.example.ts

feat: add popover tailwind example

---

apps/documentation/src/app/examples/pagination/pagination.tailwind.example.ts

feat: add pagination tailwind example

---

apps/documentation/src/app/examples/progress/progress.tailwind.example.ts

feat: add progress tailwind example

---

apps/documentation/src/app/examples/resize/resize.tailwind.example.ts

feat: add resize tailwind example

---

apps/documentation/src/app/examples/search/search.tailwind.example.ts

feat: add search tailwind example

---

apps/documentation/src/app/examples/separator/separator.tailwind.example.ts

feat: add separator tailwind example

---

packages/ng-primitives/menu/src/menu-trigger/menu-trigger.ts

…led check
-Remove duplicate disabled checks from show() and hide() methods -Improve code clarity by centralizing disable logic in one place
Closes #

change menu trigger disabled state checking

---

packages/ng-primitives/a11y/src/visually-hidden/visually-hidden.ts
packages/ng-primitives/dialog/src/dialog-overlay/dialog-overlay.ts

fix(dialog): report origin on overlay click

---

packages/ng-primitives/combobox/src/combobox/combobox.ts
packages/ng-primitives/combobox/src/config/combobox-config.ts
packages/ng-primitives/combobox/src/index.ts
packages/ng-primitives/menu/src/config/menu-config.ts
packages/ng-primitives/menu/src/index.ts
packages/ng-primitives/menu/src/menu-trigger/menu-trigger.ts
packages/ng-primitives/menu/src/submenu-trigger/submenu-trigger.ts
packages/ng-primitives/popover/src/index.ts
packages/ng-primitives/popover/src/popover-trigger/popover-trigger.ts
packages/ng-primitives/tooltip/src/index.ts
packages/ng-primitives/tooltip/src/tooltip-trigger/tooltip-trigger.ts

refactor: placement type

---

CLAUDE.md
apps/documentation/src/app/pages/(documentation)/primitives/avatar.md
packages/ng-primitives/avatar/src/avatar/avatar.ts

refactor(avatar): remove avatar interactions
